import { BLANK_TILE, type AtlasLayout, type TileId } from "../renderer/SpriteAtlas";
import { TERRAIN_COUNT, TerrainType } from "../world/TerrainType";
import { CUSTOM_TILESETS } from "./customTilesets";

/**
 * Atlas configuration and TerrainType → TileId mappings.
 * A new tile set only needs a layout + mapping (see TILESETS); nothing in
 * world/ or map/ changes.
 */

/**
 * One tile per terrain, or several variants. The variant index comes from the
 * pipeline (e.g. one floor type per building) and wraps around.
 */
export type TileMapping = Record<TerrainType, TileId | TileId[]>;

export function tileIdFor(mapping: TileMapping, terrain: TerrainType, variant = 0): TileId {
  const id = mapping[terrain];
  return Array.isArray(id) ? id[variant % id.length] : id;
}

/**
 * Terrains whose tile pattern scrolls down over time, like water in classic
 * 8-bit RPGs (the WebGL renderer shifts the tile's rows; tiles must wrap
 * vertically without a seam).
 */
export const SCROLLING_TERRAINS: ReadonlySet<TerrainType> = new Set([TerrainType.DeepWater, TerrainType.Water, TerrainType.ShallowWater]);

/** Letters for place names (A–Z → tile). An atlas without letters simply shows no names. */
export type GlyphMapping = Record<string, TileId>;


/** The placeholder atlas has one tile per TerrainType, in enum order. */
export const PLACEHOLDER_TILE_MAPPING = Object.fromEntries(
  Array.from({ length: TERRAIN_COUNT }, (_, t) => [t, t]),
) as TileMapping;

// ---------------------------------------------------------------- original tile set

/**
 * The project's own tile set, generated by scripts/make-original-atlas.mjs
 * (CC0). 16×16 tiles, 16 per row: terrain in row 0, letters A–Z from index 16.
 */
export const ORIGINAL_ATLAS_URL = "/assets/original/tiles.png";
export const ORIGINAL_ATLAS_LAYOUT: AtlasLayout = { tileWidth: 16, tileHeight: 16, offsetX: 0, offsetY: 0, columns: 16 };

const O = { deepWater: 0, water: 1, shallowWater: 2, grass: 3, scrub: 4, forest: 5, park: 6, road: 7, village: 8, town: 9, castle: 10, wall: 11, floor: 12, hills: 13, mountains: 14 };

export const ORIGINAL_TILE_MAPPING: TileMapping = {
  [TerrainType.DeepWater]: O.deepWater,
  [TerrainType.Water]: O.water,
  [TerrainType.ShallowWater]: O.shallowWater,
  [TerrainType.NarrowWater]: O.water, // never output (classified as Water)
  [TerrainType.Grass]: O.grass,
  [TerrainType.Scrub]: O.scrub,
  [TerrainType.Forest]: O.forest,
  [TerrainType.Park]: O.park,
  [TerrainType.Road]: BLANK_TILE, // plain black (the drawn road tile, O.road, is kept in the atlas)
  [TerrainType.MinorRoad]: BLANK_TILE, // never output (classified as Road)
  [TerrainType.Building]: O.village,
  [TerrainType.Urban]: O.village, // normally resolved to Building/Grass first
  [TerrainType.Town]: O.town,
  [TerrainType.Castle]: O.castle,
  [TerrainType.Wall]: O.wall,
  [TerrainType.Floor]: O.floor,
  [TerrainType.Hill]: O.hills,
  [TerrainType.Mountain]: O.mountains,
  [TerrainType.Unknown]: O.grass,
};

/** The 3×2 px flags on the original town and castle tiles (see make-original-atlas.mjs). */
export const ORIGINAL_FLAGS: FlagRects = {
  [TerrainType.Town]: [7, 1, 3, 2],
  [TerrainType.Castle]: [10, 0, 3, 2],
};

/** Creatures of the original set: two frames each from index 48, in make-original-atlas.mjs's CREATURES order. */
const CREATURE_ORDER: [string, CreatureMove, boolean?][] = [
  ["ship", "sail"],
  ["water-sprite", "swim"],
  ["kraken", "swim"],
  ["sea-serpent", "swim", true],
  ["seahorse", "swim"],
  ["whirlpool", "swim"],
  ["twister", "fly"],
  ["orc", "walk"],
  ["skeleton", "walk"],
  ["bandit", "walk"],
  ["python", "walk"],
  ["two-headed-giant", "walk"],
  ["headless", "walk"],
  ["cyclops", "walk"],
  ["wisp", "walk"],
  ["sorcerer", "walk"],
  ["lich", "walk"],
  ["fire-lizard", "walk", true],
  ["void-beast", "walk"],
  ["demon", "fly"],
  ["hydra", "walk", true],
  ["dragon", "fly", true],
  ["dark-lord", "fly"],
];

/** Tiles after the creatures: the fireball, then the 4 gate tiles, then the townsfolk. */
const FIREBALL_TILE = 48 + 2 * CREATURE_ORDER.length;
const GATE_TILES = [1, 2, 3, 4].map((k) => FIREBALL_TILE + k);
const TOWNSFOLK_BASE = FIREBALL_TILE + 1 + GATE_TILES.length;

/** Townsfolk (high zoom), two frames each, in make-original-atlas.mjs's TOWNSFOLK order, with their spawn weights. */
const TOWNSFOLK_ORDER: [string, number][] = [
  ["villager", 4], ["woman", 4], ["child", 3], ["bard", 2], ["jester", 1], ["fighter", 2],
  ["mage", 1], ["king", 1], ["beggar", 2], ["horse", 1], ["cow", 1], ["dog", 2],
];

export const ORIGINAL_CREATURES: CreatureSet = {
  defs: Object.fromEntries([
    ...CREATURE_ORDER.map(([id, moves, fire], i) => [id, { frames: [48 + 2 * i, 49 + 2 * i], moves, fire }]),
    ...TOWNSFOLK_ORDER.map(([id], i) => [id, { frames: [TOWNSFOLK_BASE + 2 * i, TOWNSFOLK_BASE + 2 * i + 1], moves: "town" }]),
  ]),
  spawn: {
    // Every sea creature is equally likely.
    deep: ["ship", "water-sprite", "kraken", "sea-serpent", "seahorse", "whirlpool", "twister"].map((id) => [id, 1]),
    shallow: ["water-sprite", "kraken", "sea-serpent", "seahorse", "whirlpool"].map((id) => [id, 1]),
    // Common creatures (orcs) are 81× as likely as the rarest (dark lord).
    land: [
      ["orc", 81], ["skeleton", 27], ["bandit", 27], ["python", 9],
      ["two-headed-giant", 27], ["headless", 9], ["cyclops", 9], ["wisp", 3],
      ["sorcerer", 27], ["lich", 9], ["fire-lizard", 9], ["void-beast", 3],
      ["demon", 9], ["hydra", 3], ["dragon", 3], ["dark-lord", 1],
    ],
    // High zoom: villagers and women are the most common, the king the rarest.
    town: TOWNSFOLK_ORDER,
  },
  fireTile: FIREBALL_TILE,
};

/** The warp gate follows the fireball: three rising stages, then open. */
export const ORIGINAL_GATE: GateDef = {
  frames: GATE_TILES,
};

export const ORIGINAL_GLYPHS: GlyphMapping = Object.fromEntries(
  Array.from({ length: 26 }, (_, i) => [String.fromCharCode(65 + i), 16 + i]),
);

// ---------------------------------------------------------------- tile sets

/**
 * Flag rectangles [x, y, width, height] inside a tile, in atlas pixels
 * (layout.tileWidth × layout.tileHeight). The WebGL renderer makes the pixels
 * inside them flutter; the rest of the tile stays still.
 */
export type FlagRects = Partial<Record<TerrainType, [number, number, number, number]>>;

/**
 * How a creature moves: sail = deep and medium water; swim = any water; walk = open land; fly = land and water;
 * town = town ground at high zoom (floors, streets, grass, parks). Townsfolk ("town") only appear at high
 * zoom (LOCAL) and the others only below it.
 */
export type CreatureMove = "sail" | "swim" | "walk" | "fly" | "town";

export interface CreatureDef {
  /** Animation frames (tile ids), cycled. */
  frames: TileId[];
  moves: CreatureMove;
  /** Breathes fire (shoots the tile set's fireTile). */
  fire?: boolean;
}

/**
 * Wandering creatures for a tile set. `spawn` lists, per kind of terrain a
 * new creature appears on, which creatures can appear and their relative
 * weights: "deep" = deep and medium water, "shallow" = shallow water,
 * "land" = open land. "town" is used instead of all three at high zoom
 * (LOCAL), for townsfolk on town ground.
 */
export interface CreatureSet {
  defs: Record<string, CreatureDef>;
  spawn: { deep: [string, number][]; shallow: [string, number][]; land: [string, number][]; town?: [string, number][] };
  fireTile?: TileId;
}

/** A warp gate: frames = rising stages, then the open gate (last). */
export interface GateDef {
  frames: TileId[];
}

export interface TilesetConfig {
  id: string;
  name: string;
  url: string;
  layout: AtlasLayout;
  mapping: TileMapping;
  glyphs: GlyphMapping;
  flags?: FlagRects;
  creatures?: CreatureSet;
  gate?: GateDef;
}

/** Selectable tile sets; the first is the default. */
export const TILESETS: TilesetConfig[] = [
  { id: "original", name: "Original (CC0)", url: ORIGINAL_ATLAS_URL, layout: ORIGINAL_ATLAS_LAYOUT, mapping: ORIGINAL_TILE_MAPPING, glyphs: ORIGINAL_GLYPHS, flags: ORIGINAL_FLAGS, creatures: ORIGINAL_CREATURES, gate: ORIGINAL_GATE },
  // Bring-your-own tile sets from tilesets/<folder>/tileset.json (git-ignored); see customTilesets.ts.
  ...CUSTOM_TILESETS,
];
